spring:
  profiles:
    active: prod
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create


# dev
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/project?characterEncoding=utf8
    username: hosung
    password: '78qorthd'
    driver-class-name: com.mysql.cj.jdbc.Driver
  error:
    nclude-exception: false
    include-message: always
    include-stacktrace: on_param
    whitelabel.enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tkddlfdlfemd@gmail.com
    password: pputllfxgpzbmunw
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
server:
  port: 8099
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK


# prod
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/project?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  error:
    nclude-exception: false
    include-message: always
    include-stacktrace: on_param
    whitelabel.enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tkddlfdlfemd@gmail.com
    password: pputllfxgpzbmunw
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
server:
  port: 8099
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK



