spring:
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: validate
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
# dev
---
spring:
  profiles: dev
  datasource:
    url: ENC(+rBt/bxt8y+cXumnX6EAw1lXuKmkjaJOBUMOx/5+b6OTGcrqL5RzMBb4vigohPa+7pYhZryfeMw2Wg6D2mtL9mkE/5Lo8xvh)
    username: ENC(5JbUcipJ4sehIVk9NX8czA==)
    password: ENC(wC+uEi3oJHt4tI/VihU2DJ+BPvLyCfAv)
    driver-class-name: com.mysql.cj.jdbc.Driver
  error:
    nclude-exception: false
    include-message: always
    include-stacktrace: on_param
    whitelabel.enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(AZC1Cc3XhzXNbBg/8W5FZ1wkMD4Jd3t8UC6BvmJyYjg=)
    password: ENC(UvQKr+FyhPN3NnASdF8YTaLAiKAXsY6GQ4Vbj2/f8WY=)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      enabled: true
      location: C:\images
      max-request-size: 100MB
      max-file-size: 10MB
server:
  port: 8099
jwt:
  secret: eyJhbGciOiJIUzI1NiJ9eyJzdWIiOiJTcHJpbmdCb290IGhzbGVlIFNpZGUgUHJvamVjdCIsImF1ZCI6ImFsbCIsIklzcyI6ImhzbGVlIiwiZXhwIjoiMjAzMC0xMi0zMVQyMzo1OTo1OSBLU1QifQRbcNEjHnJtYcV0dskYb6DbO7DgVMHFLznK8hXXwV0I


# prod
---
spring:
  profiles: prod
  datasource:
    url: ENC(H9DuKkTLj8WTegsFHI2vZpSiPxflbtfRYqJOkVoB2x9aAzyckTDhTbIIdkKJY5kcnAMhUcGA3KzhVbaGU9NYTxCTEYqBljWQ)
    username: ENC(5JbUcipJ4sehIVk9NX8czA==)
    password: ENC(wC+uEi3oJHt4tI/VihU2DJ+BPvLyCfAv)
    driver-class-name: com.mysql.cj.jdbc.Driver
  error:
    nclude-exception: false
    include-message: always
    include-stacktrace: on_param
    whitelabel.enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(AZC1Cc3XhzXNbBg/8W5FZ1wkMD4Jd3t8UC6BvmJyYjg=)
    password: ENC(UvQKr+FyhPN3NnASdF8YTaLAiKAXsY6GQ4Vbj2/f8WY=)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      enabled: true
      location: C:\images
      max-request-size: 100MB
      max-file-size: 10MB
server:
  port: 8099
jwt:
  secret: eyJhbGciOiJIUzI1NiJ9eyJzdWIiOiJTcHJpbmdCb290IGhzbGVlIFNpZGUgUHJvamVjdCIsImF1ZCI6ImFsbCIsIklzcyI6ImhzbGVlIiwiZXhwIjoiMjAzMC0xMi0zMVQyMzo1OTo1OSBLU1QifQRbcNEjHnJtYcV0dskYb6DbO7DgVMHFLznK8hXXwV0I



