spring:
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: validate
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(3KHoMgYPoGx2Mlb57xyR829NlZIe5Nku7DC/IPZzqFeE5/4rjM4L9KRJyzCXWXLlkZRPrRedaKs55NTr5K9Along+o0c02gTfrOnzNR/mXO96LeDblpFiA==)
            client-secret: ENC(4bxEW65gTJIYLcb0JpCMmtDkHFytGibdS8dtPQDwJF31pejs9MRTNbUrfrdQZbi5)
            scope:
              - profile
              - email
          #          facebook:
          #            client-id:
          #            client-secret:
          #            scope:
          #              - email
          #              - public_profile
          kakao:
            authorization-grant-type: authorization_code
            client-id: ENC(B4io5yIhD/xBsjBl8DYPWgfLnc4yY1qP07Ve/4//q2F2rClQncvHuS/IzbeTUsAD)
            client-secret: ENC(gBNW4W6Qk9rmp/WfJZfmDf03AjEvRwDxMFkE+49m8kzF2EaQ0OTYzPbqK1jm+/y5)
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
          naver:
            authorization-grant-type: authorization_code
            client-id: ENC(guGs96tdZBgKZxA6izp34KS5gYauJbSOFIq+yHOjTr4=)
            client-secret: ENC(cmngHiKF+Q2q8G58zCBs7hgzIi68JTxp)
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: name,email,profile_image
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
            # JSON 형태에서 "properties"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: id
            # JSON 형태에서 "response"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
# dev
---
spring:
  profiles: dev
  datasource:
    url: ENC(+rBt/bxt8y+cXumnX6EAw1lXuKmkjaJOBUMOx/5+b6OTGcrqL5RzMBb4vigohPa+7pYhZryfeMw2Wg6D2mtL9mkE/5Lo8xvh)
    username: ENC(5JbUcipJ4sehIVk9NX8czA==)
    password: ENC(wC+uEi3oJHt4tI/VihU2DJ+BPvLyCfAv)
    driver-class-name: com.mysql.cj.jdbc.Driver
  error:
    include-exception: true
    include-stacktrace: always
    whitelabel.enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(NJRzqMWlY8GAMTIjfU90xZjRHC6TcPjlPDj8LdaCl4U=)
    password: ENC(UvQKr+FyhPN3NnASdF8YTaLAiKAXsY6GQ4Vbj2/f8WY=)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      enabled: true
      location: C:\images
      max-request-size: 100MB
      max-file-size: 10MB
server:
  port: 8080
jwt:
  secret: eyJhbGciOiJIUzI1NiJ9eyJzdWIiOiJTcHJpbmdCb290IGhzbGVlIFNpZGUgUHJvamVjdCIsImF1ZCI6ImFsbCIsIklzcyI6ImhzbGVlIiwiZXhwIjoiMjAzMC0xMi0zMVQyMzo1OTo1OSBLU1QifQRbcNEjHnJtYcV0dskYb6DbO7DgVMHFLznK8hXXwV0I


# prod
---
spring:
  profiles: prod
  datasource:
    url: ENC(H9DuKkTLj8WTegsFHI2vZpSiPxflbtfRYqJOkVoB2x9aAzyckTDhTbIIdkKJY5kcnAMhUcGA3KzhVbaGU9NYTxCTEYqBljWQ)
    username: ENC(5JbUcipJ4sehIVk9NX8czA==)
    password: ENC(wC+uEi3oJHt4tI/VihU2DJ+BPvLyCfAv)
    driver-class-name: com.mysql.cj.jdbc.Driver
  error:
    include-exception: true
    include-stacktrace: always
    whitelabel.enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(NJRzqMWlY8GAMTIjfU90xZjRHC6TcPjlPDj8LdaCl4U=)
    password: ENC(UvQKr+FyhPN3NnASdF8YTaLAiKAXsY6GQ4Vbj2/f8WY=)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      enabled: true
      location: C:\images
      max-request-size: 100MB
      max-file-size: 10MB
server:
  port: 8099
jwt:
  secret: eyJhbGciOiJIUzI1NiJ9eyJzdWIiOiJTcHJpbmdCb290IGhbGVlIFNpZGUgUHJvamVjdCIsImF1ZCI6ImFsbCIsIklzcyI6ImhzbGVlIiwiZXhwIjoiMjAzMC0xMi0zMVQyMzo1OTo1OSBLU1QifQRbcNEjHnJtYcV0dskYb6DbO7DgVMHFLznK8hXXwV0I



